### ISSUE TITLE
Crash on restart after lamp name change (or duplicate name)

### ISSUE THREAD

**Issue by wind-rider** [thkl/homebridge-philipshue#11]
What I did:
- Installed homebridge & hue plugin
- Set up bridge ip in config.json, registered username in config.json
- Paired with phone
- Changed lamp names (and I named two lamps the same "Ceiling" since they are in different rooms anyway)

Result: homebridge+hue plugin crashes after a restart

Log:

[2016-05-14 20:18:01] Loaded plugin: homebridge-philipshue
[2016-05-14 20:18:01] Registering platform 'homebridge-philipshue.PhilipsHue'
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loaded config.json with 0 accessories and 1 platforms.
[2016-05-14 20:18:01] ---
[2016-05-14 20:18:01] Loading 1 platforms...
[2016-05-14 20:18:01] [Philips Hue] Initializing PhilipsHue platform...
[2016-05-14 20:18:01] [Philips Hue] PhilipsHue Platform Plugin Version 0.0.2
[2016-05-14 20:18:01] [Philips Hue] Fetching Philips Hue lights...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
[2016-05-14 20:18:01] [Philips Hue] Initializing platform accessory 'Ceiling'...
/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 88c675f0-a405-4b4e-b2e6-1ad5e94d45c1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-philipshue/index.js:140:9
    at resolveValue (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/hue-api/utils.js:34:13)
    at _fulfilled (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/l

My guesses at a cause:
Hue plugin thinks the renamed lamps are new lamps and need to be added?
Hue plugin thinks lamps with the same name need to have the same UUID?

**Comment by wind-rider** [comment]
It turns out this issue is caused by the UUID generation code in nodejs-HAP which generates non-unique UUIDs for accessories with the same name. Filed this issue there and in homebridge.

**Comment by wind-rider** [comment]
Please look into this issue. The plugin should guarantee that devices have unique UUIDs, otherwise it can lead to unclear problems for the users.
