### ISSUE TITLE
Terminated with Error: ETIMEDOUT

### ISSUE THREAD

**Issue by amareto** [thkl/homebridge-philipshue#19]
When starting homebridge:

Error: ETIMEDOUT
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-philipshue/node_modules/request-util/node_modules/request/request.js:919:15)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by peterjlambert** [comment]
Me too.

**Comment by peterjlambert** [comment]
Sorry. Turned out the IP address of my Hue bridge had changed. Fixed that in `config.json` (and reserved the IP on the router so it wouldn't happen again) and Homebridge started up just fine.
