### ISSUE TITLE
Terminates with error if IP of hub given and hub not present in network

### ISSUE THREAD

**Issue by DDavidMolnar** [thkl/homebridge-philipshue#2]
Hue hub IP is given in config.json. If the hub is down, at the point where lights on the hub would be set up, instead:

/usr/local/lib/node_modules/homebridge-philipshue/node_modules/q/q.js:126
                    throw e;
                    ^

Error: connect ENETUNREACH 192.168.1.107:80 - Local (0.0.0.0:50090)
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at connect (net.js:841:14)
    at net.js:937:9
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

**Comment by damianromanowski** [comment]
@DDavidMolnar @stephenyeargin It's probably best if it fails when the bridge is down. If you were to restart this when the bridge is down and it let you, all of your lights would be deleted (this includes inside scenes as well) because no accessories would be registered by the plugin. This is normal behavior.

**Comment by nriley** [comment]
Seems like a solution to that would be to cache the bridge configuration then!  Power outages happen, networks are flaky, etc.
