### ISSUE TITLE
Cannot start even after installing...

### ISSUE THREAD

**Issue by Websteria** [thkl/homebridge-philipshue#22]
This is the error I get.

sudo npm install -g https://github.com/thkl/homebridge-philipshue
homebridge-philipshue@0.0.1 /Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-philipshue
├── request@2.75.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.12, form-data@2.0.0, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)
└── node-hue-api@2.3.0 (traits@0.4.0, deep-extend@0.4.1, q@1.4.1, axios@0.8.1, xml2js@0.4.17)

[10/20/2016, 2:00:48 PM] Loaded plugin: homebridge-controllerlink
[10/20/2016, 2:00:48 PM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
[10/20/2016, 2:00:48 PM] ---
[10/20/2016, 2:00:48 PM] Loaded plugin: homebridge-philipshue
[10/20/2016, 2:00:48 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[10/20/2016, 2:00:48 PM] ---
[10/20/2016, 2:00:48 PM] Loaded plugin: homebridge-nest
[10/20/2016, 2:00:48 PM] Registering platform 'homebridge-nest.Nest'
[10/20/2016, 2:00:48 PM] ---
[10/20/2016, 2:00:48 PM] Loaded config.json with 0 accessories and 3 platforms.
[10/20/2016, 2:00:48 PM] ---
[10/20/2016, 2:00:48 PM] Loading 3 platforms...
[10/20/2016, 2:00:48 PM] Initializing HomeBridgeControllerLink platform...
[10/20/2016, 2:00:49 PM] Initializing Nest platform...
[10/20/2016, 2:00:49 PM] Fetching Nest devices.
/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'PhillipsHue' was not registered by any plugin.
    at API.platform (/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/server.js:281:45)
    at Server.run (/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/Users/jeff/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

and here's my config.json. It was all working with the nest stuff until I added the hue. The plugin did install...

{
	"bridge": {
		"name": "Homebridge",
		"username": "xx",
		"port": 51826,
		"pin": "xx"
	},
	"platforms": [{
			"platform": "HomeBridgeControllerLink",
			"doRespawn": "stopOnly"
		}, {
			"platform": "Nest",

			"token": "xx",
			"clientId": "xx",
			"clientSecret": "xx",
			"code": "xx",

			"username": "username",
			"password": "password"
		},
		{
			"platform": "PhillipsHue",
			"name": "Phillips Hue",
			"ip_address": "",
			"username": "xx",
			"excludephillips": "false"
		}
	]
}

**Comment by Websteria** [comment]
philips has one L guys... fixed.
